name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: ⚠️ Breaking Changes
    label: breaking
  - title: 🚀 Features
    label: feature
  - title: 🐛 Bug Fixes
    label: fix
  - title: 🧰 Maintenance
    label: chore

autolabeler:
  - label: 'breaking'
    regex:
      - '^breaking'
      - 'BREAKING CHANGE'
      - '^major'
  - label: 'feature'
    regex:
      - '^feat'
      - '^feature'
      - '^enhancement'
      - '^improvement'
      - '^minor'
  - label: 'fix'
    regex:
      - '^fix'
      - '^bug'
      - '^bugfix'
      - '^hotfix'
      - '^patch'
      - '^security'
      - '^vulnerability'
      - '^typo'
  - label: 'chore'
    regex:
      - '^chore'
      - '^refactor'
      - '^docs'
      - '^style'
      - '^test'
      - '^ci'

version-resolver:
  major:
    labels: ['major', 'breaking']
  minor:
    labels: ['feat', 'feature']
  patch:
    labels: ['fix', 'bug', 'chore']
  default: patch

template: |
  ## What’s Changed
  
  $CHANGES
